name: printbot
main: org.printcraft.printbot.PrintBot
version: 1.1b
depend: [WorldEdit, WorldGuard, WGCustomFlags]
commands:
  printbot_print:
    description: Prints a WorldGuard region
    usage: /printbot_print regionName
    alias: printbot print 
  printbot_clear:
    description: Clears a WorldGuard region
    usage: /printbot_clear regionName
    alias: printbot clear
  printplot_claim:
    description: Claims a WorldGuard region
    usage: /printplot_claim regionName
    alias: printplot claim
  printplot_unclaim:
    description: Unclaims a WorldGuard region
    usage: /printplot_unclaim regionName
    alias: printplot unclaim
  printplot_create:
    description: Creates a printplot on a WorldGuard region
    usage: /printplot_create regionName
    alias: printplot create