name: printplot
main: org.printcraft.printplot.PrintPlot
version: 1.1b
depend: [WorldEdit, WorldGuard, WGCustomFlags]
commands:
  printplot_claim:
    description: Claims a WorldGuard region
    usage: /printplot_claim regionName
    aliases: ppclaim
  printplot_unclaim:
    description: Unclaims a WorldGuard region
    usage: /printplot_unclaim regionName
    aliases: ppunclaim
  printplot_add:
    description: Adds a player to a your plot
    usage: /printplot_add playerName
    aliases: ppadd
  printplot_remove:
    description: Removes a player to a your plot
    usage: /printplot_remove playerName
    aliases: ppremove
  printplot_create:
    description: Creates a printplot on all worldguard regions with a number
    usage: /printplot_create
    aliases: ppcreate
    